use_frameworks!

platform :ios, '8.0'

target 'JOWCategory_Example' do
  pod 'JOWCategory', :path => '../'

  target 'JOWCategory_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
